parameters:
- name: SolutionName
  type: string
  default: ''
- name: InstallDependencies
  type: boolean
  default: false
- name: TestProjectsPath
  type: string
  default: ''

jobs:
- job: TestJob
  steps:
  - template: parameter-check-v1.yml
    parameters:
      Name: SolutionName
      Value: ${{ parameters.SolutionName }}
  
  - template: steps-dotnet-test-v1.yml@sharedTemplates
    parameters:
      SolutionName: ${{ parameters.SolutionName }}
      InstallDependencies: ${{ parameters.InstallDependencies }}
      TestProjectsPath: ${{ parameters.TestProjectsPath }}